name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

  launching-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Connect to AWS instance
        uses: appleboy/ssh-action@master
        with:
          host: 13.37.252.210
          username: Pierre Scheldewaert
          key: ${{ secrets.AWS_SERVER_KEY }}
          password: hackerman
          script: |
            git pull git@github.com:Pierre-ui/ci-cesi.git
            pm2 start npm -- run start
    

