name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path:
            - node_modules
            - /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path:
            - node_modules
            - /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run E2E tests
        run: npm run e2e:headless
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: e2e-video
          path: cypress/videos/
