name: Building App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16'

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          browser: chrome

      - run: npm install
      - run: npm run build
      - run: ls -la
